# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(424, 154)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.get_date = QtWidgets.QPushButton(self.centralwidget)
        self.get_date.setGeometry(QtCore.QRect(60, 100, 201, 31))
        self.get_date.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.get_date.setObjectName("get_date")
        self.search_text = QtWidgets.QLabel(self.centralwidget)
        self.search_text.setGeometry(QtCore.QRect(120, 10, 151, 21))
        self.search_text.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.search_text.setTextFormat(QtCore.Qt.AutoText)
        self.search_text.setAlignment(QtCore.Qt.AlignCenter)
        self.search_text.setObjectName("search_text")
        self.dataset = QtWidgets.QPushButton(self.centralwidget)
        self.dataset.setGeometry(QtCore.QRect(280, 100, 75, 31))
        self.dataset.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.dataset.setObjectName("dataset")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(50, 40, 321, 51))
        self.dateEdit.setObjectName("dateEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Window"))
        self.get_date.setText(_translate("MainWindow", "Получить данные"))
        self.search_text.setText(_translate("MainWindow", "Выберите дату:"))
        self.dataset.setText(_translate("MainWindow", "Датасет"))
